version: '3.1'

services:

  splash:
    # TODO: Need to create more instances to increase productivity
    # TODO: Create a simple flask app to check if splash containers are alive and to restart if it is necessary
    image: scrapinghub/splash
    command: --maxrss 4096 --max-timeout 300 --disable-ui -v 4 --disable-private-mode
    restart: always
    ports:
      - 8050:8050

  searx:
    image: searxng/searxng
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng
    environment:
      INSTANCE_NAME: mobile_parts_companies

  app:
    image: ferhadferrytelecom/mobile_parts_companies
    restart: always
    volumes:
      - ./:/usr/src/app
